-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        active_opacity = 0.83,
        blur = {
            passes = 3,
            size = 9,
        },
        dim_inactive = true,
        dim_strength = 0.55,
        rounding = 6,
        rounding_power = 3.3,
    },
    general = {
        gaps_in = 3,
        gaps_out = 9,
        layout = "dwindle",
    },
})
