foreground #e0e3e8
background #101417

cursor #97ccf8
selection_foreground #00344f
selection_background #97ccf8

color0  #1c2024
color1  #ffb4ab
color2  #d0bfe8
color3  #b8c8d9
color4  #97ccf8
color5  #b8c8d9
color6  #d0bfe8
color7  #e0e3e8

color8  #41474d
color9  #ffb4ab
color10 #d0bfe8
color11 #b8c8d9
color12 #97ccf8
color13 #b8c8d9
color14 #d0bfe8
color15 #e0e3e8
